/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:8aff1bac-52c5-4294-ab73-bbb212f771e2",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_QeFQ8tkFA",
    "aws_user_pools_web_client_id": "5mkrsvnvr2v7pnueqg43c2i0a3",
    "oauth": {}
};


export default awsmobile;
